### ISSUE TITLE
upload wasm, get sha256 has handle

### ISSUE THREAD

**Issue by kevingzhang** [TeaRUST/tee-on-mac#2]
after client upload a wasm file.
Get the sha256 of the wasm file
use the hash as handle for future usage:
- as the key of kvpair when cache compiled wasm binarys
- return to the client after upload wasm.
- Client will use this handle as parameter to call any function inside this wasm

Considerations:
1. We do not have the sha256 of the compiled binary because that the compiled binary may be vary in different CPU arch. The client only cares about the wasm source binary code.
2. We cannot use the file name of wasm as handle, because there might be different version of the same wasm file. Also, hacker may modify the wasm code as phishing code.

From the clients side. After upload the wasm, server returns a sha256 string. Later, when client wants to call "add" function, he will need to post a request including the following parameters:
- hash of the wasm
- parameters
Tee returns : 
- result
- signature of this computation
- gas usage

we will deduct gas cost later, but for now, just return the gas consumed.

**Comment by kevingzhang** [comment]
do not store persistently. Just cache compiled mod in memory using a Hashmap.

**Comment by liyangwood** [comment]
closed
