### ISSUE TITLE
Build google tpm-js and use its tpm simulator wasm file in our project

### ISSUE THREAD

**Issue by kevingzhang** [TeaRUST/tee-on-mac#5]
https://google.github.io/tpm-js/#pg_welcome  is a google side project. It provides TPM simulator on js for educational purposes. 

It compiles the cc code to wasm and run in a python server serve to js front end.
I am thinking to reuse the wasm in our project so that we can simulate a TPM in our TEE.

However, I am unlucky when building the project from source https://github.com/google/tpm-js

I do not know if I miss anything.

Please try to build it on your own machine, let me know if it works.

If it works, try to do some research to see if we can use the wasm as our own software TPM simulator

**Comment by yz89** [comment]
I compiled it successfully.

I met this problem during compilation:
```
Traceback (most recent call last):
  File "/Users/yzhou/github/tpm-js/tools/template_builder.py", line 18, in <module>
    import jinja2
ImportError: No module named jinja2
make[2]: *** [web/index.html] Error 1
make[1]: *** [CMakeFiles/index.html.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
and fixed it via: 
```
pip install jinja2
```

**Comment by liyangwood** [comment]
closed
